
const array = [
    {
        year: "1936",
        sections:[
            {
                sectionName: "The Americas",
                sectionHeaders:[
                    {
                        header:"The United States and Canada",
                        sectionBody:[
                            "During the years leading up to 1936, two political parties built up enough political support to rival the likes of the Democrats and Republicans. These were the Socialist Party of America headed by John Reed and the America First Party headed by Huey Long. The SPA were supporters of Syndicalism and left leaning ideologies that advocated for the workers of America and wished to bring about a Syndicalist revolution, while the America First Party was a right leaning party formed by Huey Long in hopes of implementing the party’s Share Our Wealth program and were highly against the SPA. ",
                            "When Black Monday hit the US economy, a previously shot down bill reintroduced into the senate in hopes of its policies being able to alleviate the damage done by the Black Monday. The Garner-Wagner Bill was promised to be the bill that can help jump start economic recovery, however the bill had trouble gaining support in the senate due to conflicting interests between the SPA and AFP. With this, the Republicans and Democrats agreed to form a coalition government in order to counteract the rising influences of the SPA and AFP as well as having a better chance at maintaining order. This move was able to put more support behind the Garner-Wagner bill with further support gained by compromising with the SPA to modify the bill to include more worker friendly policies. Yet in the end the bill was shot down, angering both the AFP and SPA.",
                            "As months went on, violence within the nation began to dramatically rise. Influence for both the SPA and AFP began to grow as more senate seats were given to each respective party due to state elections. Violence between the SPA and AFP had gotten so high that the national guard were called in various states to help break up clashes between supporters. At the same time, cracks began to form within the Republican-Democrat coalition, but these rifts would be temporarily mended as the coalition focused on maintaining what power they have left within the states as the election of 1936 comes in. ",
                            "When November 1936 rolled around, the elections were mired with controversy, but none were more controversial as when the AFP candidate Huey Long wins the election. Immediately the SPA contested the results, citing voter fraud and refused to recognize the AFP’s victory. Now former president Herbert Hoover criticized the winner, saying that this choice would bring upon a dangerous future for the nation. In protest of the election results, the SPA declares a strike for New Years Day, crippling the US as the nation heads into 1938. After President Long’s inauguration his first orders were to ban the SPA from the government. Unsurprisingly this angered the SPA who refused to recognize his presidency. The SPA’s anger would only increase from here as one of president Long’s executive order was to label the SPA as a terrorist organisation, this was deemed unconstitutional by the SPA and was the last straw for the party, cutting all communication to Washington. The state of the US at this point was on the brink of collapse, in order to restore order, General MacArthur of the US Armed Forces marched on Washington DC to remove President Long on the grounds of being unable to perform the duties of a constitutional president. However, due to an informant in the military, President Long had already fled Washington, making his way down to Baton Rouge. MacArthur was later sworn in as provisional president until the nation can be stabilized. ",
                            "Yet the move to march on the capital would be the tipping point that would plunge the US into further fracturing along party lines. When President Long arrived in Baton Rouge, Louisiana, he declared that MacArthur and the SPA were traitors and enemies to the US, and that states should side with him as he claimed to be the legitimate winner of the 1936 US elections. From this address the American Union State would be established and officially secede from the US. multiple states in the US deep south would pledge their allegiance to President long and the Union State, which included states from Texas to Alabama to South Carolina. ",
                            "The SPA would respond with a similar message, except directed towards Huey and MacArthur, in order to bring about the Syndicalist revolution, the SPA established the Combined Syndicates of America basing themselves out of Chicago. Several states along the Steel Belt pledged their allegiance to the CSA, joining with Chicago and seceding as well.",
                            "Seeing the threat that is upon the nation as well as an apparent subversion of the US’s democratic ideals, the Pacific states of California, Oregon, and Washington State declared that the SPA, AFP, and MacArthur in Washington were all enemies of the US and democracy, while not necessarily seceding from the US, the Sacramento lead Pacific States of America pledged that it will defeat the enemies in Baton Rouge, DC, and Chicago in order to save the US and preserve a true democracy. ",
                            "In response to the rebel states declaring their intentions, General MacArthur issued the 30 day deadline, an ultimatum to each rebel state to stand down and disarm before the federal government will have to intervene and force the rebels to disarm. Yet he and everyone knew that this ultimatum would fall upon deaf ears was the factions of America now face each other in a standoff as everyone tries to seize as much land as they can before open conflict begins.",
                            "The Standoff began with the CSA seizing control of Minnesota as Syndicalist militias march on Minneapolis. North Carolina would pledge its support for the Union State while Tennessee would be forcefully integrated by Longist militia. Federal forces secure New Jersey, kicking out syndicalist militias trying to take control to allow access to New York City. The Western states past the Mississippi that remained loyal to MacArthur in Washington stood their ground against any rebel state as the General vowed to protect them, but still every military installation was abandoned as the army moved east to fortify Virginia.  The states in the New England despite remaining loyal to Washington had secretly approached the Canadians to occupy New England as they did not want to endanger their people in the upcoming civil war. Meanwhile, Federal forces were forced out of Southern Texas and Iowa pledged its allegiance to the CSA. From there, the borders solidified and as the deadline comes to an end on the 3rd of April 1937, shots were fired across the nation as the Second American Civil War begins.",
                            "Acting on the wishes of the New England governors, the Canadians moved in and occupied New England, establishing the Provisional Republic of New England under the protection of Canada and the Entante. The three rebel nations scramble to grab as much of the west as they can as Washington  fortifies and holds their positions on the Appalachian mountains or Virginia and the northern borders of Maryland."
                        ]
                    },
                    {
                        header:"The Second American Civil War",
                        sectionBody:[
                            "Soon after the start of the civil war, the three rebel nations rushed to seize as much of the west as they possibly can. By July of 1937 the west was fully occupied by rebel forces. The Pacific States managed to take the states of Arizona, Idaho, Nevada, Utah, Colorado, Montana, Wyoming, and western New Mexico. The CSA managed to grab the Dakotas, Nebraska, and Northern Kentucky, while the Union State secured Eastern New Mexico, Kansas, and southern Kentucky. All the while the Federal government received support from the Entante, sending equipment and volunteer forces to help strengthen MacArthur’s government.  However on the CSA’s side was the Third Internationale who similarly sent men and equipment to the Chicago in hopes of securing a strong future ally for the Internationale in the future. ",
                            "As the war went on into August and September of 1937, the western frontlines fought between the CSA, Union State, and Pacific States remained stagnant. In the meanwhile, Federal forces began rapidly advancing against the CSA, making a push towards Lake Erie and cutting off a large part of the CSA army including New York City. It took another 4-6 months for the Pennsylvania pocket to be cleaned out however as Syndicalist forces remained strong in places such as Philadelphia and New York City. By January 1938, the Federal forces marched west towards Cleveland, this move caught the CSA off guard, costing them dearly as the Internationale volunteers were trapped in an encirclement and destroyed. Meanwhile in the west, the front remained stagnant in the north between the Pacific States and the CSA. However, a major development in the south with the Union State hit as the Pacific States managed to a breakthrough in northern New Mexico putting the entire front at stake. ",
                            "The Pacific State’s breakthrough in New Mexico quickly spiraled out of control for the Union State, due to logistical challenges and equipment shortages, the Pacific States faced little challenged as they maintained their momentum into Texas, driving a wedge between Texas and Baton Rouge as the Pacific States reach the Gulf of Mexico by July of 1938. The Pacific states at the same time conducted an offensive into Minnesota, capturing Minneapolis and pushing into Iowa. The Federal government also took advantage of the situation and launched an offensive to capture key regions of Ohio, including the city of Columbus.",
                            "After securing Texas in Aug 1938, the Pacific States pushed towards Baton Rouge, by now the Union State’s army is in no position to stop their offensive and thus were on the backfoot in the civil war. Taking advantage of this, the federal government also conducted an offensive down the east coast, capturing North Carolina and pushed towards Charleston in South Carolina. Baton Rouge would be captured by the Pacific States during April of 1939, Federal forces in the meantime managed to secure Georgia and Florida as well as pushing towards Birmingham in Alabama. With no way to stop the collapse of the east and the west, the Union State surrenders during June of 1939. ",
                            "Attention was now focused on eliminating the CSA, Pacific and Federal forces were redeployed towards the Steel Belt and a massive offensive was launched by the Federal government to capture Chicago before the Pacific States. The Federal government managed to capture Detroit and Gary but were not able to reach Chicago in time before the CSA surrendered in October of 1939. ",
                            "With the CSA and the Union State gone, the two remaining factions fought in a bitter struggle as the frontlines reached the Mississippi River by December of 1939. Yet through superior tactics and the support of the Entante, Pacific forces were systematically encircled and destroyed, severely reducing their capabilities to hold the line at the Mississippi. By February of 1940, a massive offensive across the entire frontline took place and pierced the Pacific State’s frontlines. Unable to form a proper defensive line past the Mississippi, the Federal forces continued to encircle and destroy many Pacific division, by June of 1940, the Pacific States were pushed back to Denver and at this point, unable to fully secure the frontline stretching from Eastern Montana to Western Texas. Yet despite being out numbered, the Pacific States fought on until the end, it took until October 4th 1940 for the Federal forces to reach the West Coast and force the Pacific government to surrender. ",
                            "As the civil war comes to a close, the US was left with economic and political wounds, but the Federal Government that came out of the civil war and reconstruction wouldn’t resemble anything like the Federal Government of 1937 and the before. During a speech on November 4th 1940, president MacArthur announced to the public that he would not be stepping down as president of the United States until the “wounds of the civil war would be fully healed”. Many did not take this news kindly and riots across the sprang up in protest of MacArthur’s decision. yet they would all be quelled with relative ease as the military strengthened its grip on civilian life. Over the next 5-7 years of reconstruction, the US and its democratic ideals would be slowly but surely stripped away as it slipped into an era of military dictatorship. Replacing the American Democracy with an American Stratocracy helmed by MacArthur. The US would not see its democracy restored until German troops captured Washington DC during the last months of the Third Weltkreig."
                        ]
                    },
                    {
                        header:"Other Events in the Americas",
                        sectionBody:[
                            "text text etx tetdsdyskdhhksd sdifhsd kf lkjdsfh sadk f ksd f  fsdjkfhjksdkj fs hdfsdhfsjd f jskfjk sdfh sk dfj sdjfk",
                            "text kjsdnf sdfj s dfjk;lsfk sf sdfk sdf;jklsjdf l;skdj fsdfkjksdjfskl;d fj sdkfljdslkfjsldkf jsdkfj skfsdkf sfj sdf dskfds f dsfsdkj fsdfksd fsdkjfdk fj sld fjsdkfkslkfkldsklfjlsdlvlkskvjlks dsdf sjkf sf sd fs fsk fsf d fjskl fslf"

                        ]
                    },

                ]
            },
            {
                sectionName: "Europe",
                sectionHeaders:[
                    {
                        header:"The Spanish Civil War",
                        sectionBody:[
                            "text text etx tetdsdyskdhhksd sdifhsd kf lkjdsfh sadk f ksd f  fsdjkfhjksdkj fs hdfsdhfsjd f jskfjk sdfh sk dfj sdjfk",
                            "text kjsdnf sdfj s dfjk;lsfk sf sdfk sdf;jklsjdf l;skdj fsdfkjksdjfskl;d fj sdkfljdslkfjsldkf jsdkfj skfsdkf sfj sdf dskfds f dsfsdkj fsdfksd fsdkjfdk fj sld fjsdkfkslkfkldsklfjlsdlvlkskvjlks dsdf sjkf sf sd fs fsk fsf d fjskl fslf"

                        ]
                    },
                    {
                        header:"The Fourth Balkan War",
                        sectionBody:[
                            "Bulgaria came out of the First Weltkreig with a massive expansion of its territory at the expense of its neighbours. Thus the nation went into the interwar period in a precarious situation. Serbia would be the nation that would lead in the dismantling of Bulgaria’s new empire. On the 21st of Oct 1936, Serbia held the Congress of Belgrade, inviting Romania and Greece to discuss details relating to a possible war with Bulgaria to reverse the territorial changes of the First Weltkreig. Romania and Greece agreed with Serbia and in turn the nations formed the Belgrade Pact, to stand against Bulgaria. ",
                            "For the next couple months, Serbia would prepare itself for a war against Bulgaria, preparations include, bringing back conscription, fortifying the border along the Morava River, and equipping partisan forces in the states of Nish and Macedonia. On the 6th February 1937, Serbian forces crossed the Morava River, starting the Fourth Balkan War, Greece and Romania would also declare war on Bulgaria a few hours later. ",
                            "Surrounded on three sides, the Bulgarian’s strategy was to stop Romania and Serbia from linking up as well as wiping the Greek garrisons of Thessalonica. The first few weeks of the war were in Bulgaria’s favour, the Belgrade pact had underestimated Bulgaria’s capabilities and were unable to advance into their respective fronts. Things would change when the Ottomans intervened in the war against Bulgaria, causing troops to be pulled from other fronts in order to stop the Ottomans from advancing in the south. Ottoman intervention gave the Belgrade pact a chance to advance into Bulgarian territory, allowing for Romania and Serbia to link up forces and Greece to push in as well. But the Ottomans wouldn’t be in the war for long, as the Bulgarians managed to secure a white peace with the Ottomans in exchange for handing over Eastern Thrace, focusing all Bulgarian troops back towards Serbia and their allies. ",
                            "Seeing that reinforcements from the Ottoman front would be coming back, Romania made a daring offensive into central Bulgaria, pushing deep until they reached the outskirts of Plovdiv and Sofia. This proved to be crucial for the Belgrade pact’s war effort as now the Bulgarian forces are scrambling to secure this spearhead, allowing for Serbia to advance closer to Sofia. During the last week of May 1937, a joint offensive effort between Serbia and Romania fought with Bulgarian forces to try and secure Sofia, Bulgarian forces fought as hard as they can, but would lose the city on May 31st 1937. Soon after, Bulgarian diplomats called for a ceasefire and conceded to the Belgrade pact’s demands to cede all lands gained from the first Weltkreig back to Serbia and their allies. ",
                            "The Fourth Balkan War would prove to be the one of Bulgaria’s darkest moments as their brief moment of Balkan hegemony was crushed by a coalition of its rivals. The monarchy was later abolished for a republic and Bulgaria would later align itself with the Austrians when the Donau-Adribund was formed. As for Serbia, Greece, and Romania, the Belgrade pact would later be disbanded as its goals have been accomplished, Greece and Serbia would later join the Moscow pact when the Russian Republic formed it. Romania in the meanwhile remained out of the Russian’s alliance as they pursued a more nationalist ideology, hoping to one day reclaim Transylvania from the Danubian Federation. "
                        ]
                    },
                    {
                        header:"The Leadup to the War",
                        sectionBody:[
                            "text text etx tetdsdyskdhhksd sdifhsd kf lkjdsfh sadk f ksd f  fsdjkfhjksdkj fs hdfsdhfsjd f jskfjk sdfh sk dfj sdjfk",
                            "text kjsdnf sdfj s dfjk;lsfk sf sdfk sdf;jklsjdf l;skdj fsdfkjksdjfskl;d fj sdkfljdslkfjsldkf jsdkfj skfsdkf sfj sdf dskfds f dsfsdkj fsdfksd fsdkjfdk fj sld fjsdkfkslkfkldsklfjlsdlvlkskvjlks dsdf sjkf sf sd fs fsk fsf d fjskl fslf"

                        ]
                    }
                ]
            },
            {
                sectionName: "Africa and the Middle East",
                sectionHeaders:[
                    {
                        header:"The War in the Desert",
                        sectionBody:[
                            "The War in the Desert was a war fought between the Cairo Pact and the Ottoman Empire, it was a war to determine whether the Middle East would be united by Arab nationalism or united under an Ottoman Federation. During the months leading up to the war, the Kingdom of Egypt hosted the Third Arab Congress, initially a peaceful congress aimed at celebrating Arab culture, the congress has now become a Egypt’s way to cement itself as the nation that would liberate Arabs from oppression, a clear jab at the Ottoman’s rule over the Levant and Arab Peninsula. The next 11 months would see Egypt secretly fund resistance cells within Ottoman controlled Syria, Iraq, and other areas of the Middle East as well as arming potential allies in Yemen and Cyrenaica. On the 18th of December 1938, the Cairo Pact was formed between Egypt and Cyrenaica who had recently aligned with Egypt. 5 days later on the 23rd of December 1938, Ottoman troops would come to occupy the Mutasarrifate of Jerusalem, after the abolishment and the reintegration of the state back into the Ottoman Empire. The Egyptians demanded that the Sinai Peninsula be ceded back to Egypt as Jerusalem was occupying it when it was still a mandate yet the Ottomans didn’t budge. The International Congress in the MOJ agreed with Egypt and demanded that if the MOJ was to be reintegrated back into the Ottoman Empire, the Sinai Peninsula should at least be returned to Egypt. Yet Ottoman troops still marched towards the Sinai, prompting Egyptian forces to cross the Suez Canal to occupy the Sinai themselves. When the two armies met, gun shots were exchanged and all out war ensues, the War in the Desert had begun.",
                            "As the war began, Egyptian backed Syrian rebels rose up and formally join the Cairo Pact, disrupting Ottoman supply lines to the lower Levant. The Ottomans would quickly occupy Palestine and the Egyptians occupied the Sinai. As the war raged on into the new year, several countries and rebel groups would see their opportunity to destroy the Ottoman Empire, now reformed into the Sublime Ottoman Federations. The first to intervene was Yemen who joined in on the 3rd of January 1939. Iran also intervened in hopes of destroying the Ottoman Empire, lastly, Armenian rebels rising up in the north east near Yerevan on the 28th of January 1939.  The frontlines stayed stagnant during January 1939, until the Sultanate of Ha’il betrays the Ottomans and join up with the Cairo Pact on the 20th February 1939, this caused the Ottomans to pull back from Yemen and Egypt to not risk troops becoming encircled. ",
                            "After pulling back to a more defensible position in Syria, the Ottomans made a push into the Arabian Peninsula, hoping to quickly knock out Ha’il and refocus attention towards Egypt. Ha’il did not expect this thrust and the sultanate’s troops were quickly overwhelmed. To counteract the Ottoman offensive, the Egyptians launched their own offensive into Syria with varying degrees of success. Yet Ottoman forces pressed on, managing to force Ha’il to capitulate after capturing their capital on the 8th of May 1939.  The Ottomans now moved their troops forwards and pushed the Egyptians back, the Egyptians were unprepared for this counterattack and were unable to form a defensive line, thus they were pushed back behind the Suez Canal. At the same time, Iranian troops push towards Baghdad and succeed at capturing the city, but were unable to advance deeper into Iraq as Ottoman reinforcements shored up defenses in Iraq and prepared to retake the Baghdad. ",
                            "During July of 1939, two offensives took place in both the Iranian front and the Egyptian front. On the Iranian front, the Ottomans began their counter attack in Iraq, recapturing Baghdad on 15 July 1939 and managing to continue their offensive into Iranian territory, this breakthrough allowed the Ottomans to seize the valuable Iranian oil fields and had spread Iranian forces thin. However, it would take until August 1939 for the Ottomans to capture Tehran and force the Iranians to the negotiation table. At the same time at the Egyptian front, several offensives took place along the Suez Canal trying to pierce Egyptian defenses to cross the canal. These were mostly ineffective as the canal proved to be quite challenging to cross. Thus a new plan was to take place, Ottoman troops launched a naval invasion of of the Nile Delta behind Egyptian lines, catching Egyptian troops off guard and gave an opportunity for Ottoman troops to cross the Suez. Once the frontlines were reorganized, Ottoman forces launched an offensive towards Cairo, capturing the city by October of 1939. With their capital gone, the Egyptians were on the backfoot, they quickly tried to fortify positions around Alexandria and down the Nile, but Ottoman troops at this point were unstoppable, capturing Alexandria and much of the Nile by November 1939. on the 13th of November 1939, the Cairo Pact would formally surrender, ending the War in the Desert. ",
                            "The Ottomans decided to annex and integrate the the Cairo Pact into the Ottoman Federation. Iran in the meanwhile would be reorganized into an Ottoman puppet state, with its western states ceded to the Ottomans. The Ottomans would later align with the Germans, formally joining the Reichspakt and joining the Second Weltkrieg against the Internationale and the Moscow Pact. The lessons learned in the War in the Desert would prove to be valuable to the Ottomans, performing exceptionally well against Russia in desert regions such as the Central Asia."
                        ]
                    }
                ]
            },
            {
                sectionName: "Asia and the Pacific",
                sectionHeaders:[
                    {
                        header:"The Chinese Warlord Era",
                        sectionBody:[
                            "From the outside, China seems to be united under Beijing and the Qing Empire, however the world would see what was under the curtain when Black Monday hit China, shattering Beijing’s fragile control over its states. ",
                            "Almost immediately after the collapse of Qing control, the League of Eight Provinces, a union of states situated upon China’s east coast, fractured further into smaller states. There were four states fighting to secure Eastern China for themselves. Located in the south was the MinGan Insurgency, a Socialist rebel group which drew its roots from the Republic of China and the Kuomintang, they were driven into hiding in the previous few years but due to the recent chaos in the league, they have gone out of hiding and risen up for one final struggle. In the north of the League lies the two warlords fighting each other to secure the league, the Nanjing Clique is the remnant of the league’s government, fighting to secure their control in hopes of stabilizing the region. The Anqing Clique is a rival warlord faction that hopes to re-establish the league in a different direction. To the north in Shandong province lies the Shandong clique, in the mists of chaos, it wishes to expand its influence to the south. ",
                            "Despite the struggles between all the factions of the league, the Nanjing clique managed to come out on top due to German volunteers. The MinGan Insurgency was the first to surrender as German forces captured Longyan, forcing the rebels to retreat into the mountains once again. Anqing would be the next to fall after forces from the Nanjing and Shandong Cliques focused its efforts on capturing Anqing after it had accepted help from the Fengtian Clique and the Japanese. The Shandong Clique was the last to fall after being overwhelmed by a combined offensive with Nanjing and German forces. The Nanjing clique was able to stabilize the region and reform itself into the League of Southeast Provinces.",
                            "Despite the collapse of the Qing Empire, the Qing government was able to secure its position in Beijing and in the lands of the Zhili Clique. From there the Qing government was able to recover from Black Monday and started to re-establish control over the rest of China, by 1939, many warlords in places such as Shanxi, Sichuan, and the League of Southeast Provinces had agreed to become subjects of the Qing government. One warlord that stood as a rival to the Qing were the Fengtien Clique, located in Manchuria. The Fengtian Clique is the last remnant of the Republic of China, claiming to be the last bastion of China’s democracy, the state has become an authoritarian state that stood opposed to the Qing government. The clique is also influenced by the Japanese Empire through treaties and investments. The Japanese hope that with enough influence in the Fengtian it could potentially be able to influence the rest of China, propelling Japan and its future ambitions into greater heights. ",
                            "This rivalry between the Qing and the Fengtian would inevitably lead to the war breaking out between the two rival governments. Initially the war was initially limited between the Qing and Fengtian but then quickly spiralled out of control, the Japanese Empire intervened on the side of the Fengtian, helping to push back Qing forces back towards the initial border. In response to this intervention, the Qing Government issued a call to arms to all Chinese warlords to join the Qing in the struggle against Japanese Imperialism. The now labelled 2nd Sino-Japanese War would turn into a meat grinder as the war dragged on until 1948, mostly due to the outbreak of the Second Weltkrieg.",


                        ]
                    },
                    {
                        header:"The Indian War of Reunification",
                        sectionBody:[
                            "Before 1936, the British Raj experienced its own revolution as the British Isles fell into Syndicalist hands. During this tumultuous period on the sub-continent, what remains of the British control was consolidated into the north west, establishing the Dominion of India centered in Delhi. The East in Bengal as well as just south of the Dominion of India was swept up by the Bharatiya Commune, a Syndicalist nation which was inspired to take up arms after what happened in Britain and France. As the collapse of the British Raj continued, princes in Southern India joined together in a federation to protect their lands from the ensuing chaos of the revolution. Eventually this federation was able to stabilize southern India and spared it from the chaos of collapsing British authority. The Princely Federation, as it is called, was the most peaceful out of the three nations that came out of the collapse of India.",
                            "As the years past 1936 go on, tension between the three states started to rise, particularly with the Bharatiyans and the Dominion of India as they are sworn enemies of each other. This would inevitably bring the two nations to war on the 26th of June 1937. Not wanting a successful syndicalist revolution, the Princely Federation sided with the Dominion of India and declared war on the commune approximately one month after on the 26th of July 1937. Over the course of six months, the fighting between the Bharatiyans and a combined Dominion and Princely troops successfully defeat the commune after successfully capturing the Capital in Calcutta. Yet the war would not be over as the two remaining states would fight against each other to determine the fate of India.  All fighting would stop when the Princely Federation was successfully occupied by dominion and Entante forces on the 17th of May 1939. The Dominion of India would go on to become one of the Entante’s dominant power in Asia and support the British and French efforts in to retaking their homeland.",
                        ]
                    }
                ]
            }            
        ]


    },
    "hello there",
    "hey there",
    "bye bye"
]
export async function GET(request){
    const requestUrlSplit = request.nextUrl.pathname.split("/")
    console.log(array[requestUrlSplit[requestUrlSplit.length-1]])
    if (requestUrlSplit[requestUrlSplit.length-1] < array.length && requestUrlSplit.length > 0){
        return new Response(JSON.stringify({message: array[requestUrlSplit[requestUrlSplit.length-1]]}, {headers: { 'Content-Type': 'application/json' }}))
    } else {
        return new Response(null, {status: 400, headers: { 'Content-Type': 'application/json' }})
    }
}